apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-defaultchannel-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-defaultchannel-aais
  chart:
    git: https://github.com/suryalanka-cy/openidl-aais-gitops
    ref: aais-nd-poc
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.prod.aais.uim.openidl.org:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.prod.aais.internal.uim.openidl.org
      authpath: prodaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: defaultchannel      
    orderer:
      address: orderer1.ordererorg.prod.aais.uim.openidl.org:8443
    anchorstx: |-
      CtYCChwKGggCGgYI7auImQYiDmRlZmF1bHRjaGFubmVsErUCCrICCg5kZWZhdWx0Y2hhbm5lbBJg
      El4KC0FwcGxpY2F0aW9uEk8IARJLCgdhYWlzTVNQEkAaBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsK
      B1dyaXRlcnMSACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVudBIAGr0BEroBCgtBcHBsaWNhdGlv
      bhKqAQgBEqUBCgdhYWlzTVNQEpkBCAEaBwoDTVNQEgAaTQoLQW5jaG9yUGVlcnMSPhI0CjIKLXBl
      ZXIwLmFhaXMtbmV0LmFhaXMucHJvZC5hYWlzLnVpbS5vcGVuaWRsLm9yZxD7QRoGQWRtaW5zIgsK
      B1JlYWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACoGQWRt
      aW5z

