apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-defaultchannel-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-defaultchannel-aais
  chart:
    git: https://github.com/suryalanka-cy/openidl-aais-gitops
    ref: aais-nd-poc
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.aais.nd-poc.uim.openidl.org:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.nd-poc.uim.openidl.org
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: defaultchannel      
    orderer:
      address: orderer1.ordererorg.dev.aais.nd-poc.uim.openidl.org:8443
    anchorstx: |-
      CtwCChwKGggCGgYIytGAmQYiDmRlZmF1bHRjaGFubmVsErsCCrgCCg5kZWZhdWx0Y2hhbm5lbBJg
      El4KC0FwcGxpY2F0aW9uEk8IARJLCgdhYWlzTVNQEkAaBwoDTVNQEgAiDwoLRW5kb3JzZW1lbnQS
      ACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoKBkFkbWlucxIAGsMBEsABCgtBcHBsaWNhdGlv
      bhKwAQgBEqsBCgdhYWlzTVNQEp8BCAEaUwoLQW5jaG9yUGVlcnMSRBI6CjgKM3BlZXIwLmFhaXMt
      bmV0LmFhaXMuZGV2LmFhaXMubmQtcG9jLnVpbS5vcGVuaWRsLm9yZxD7QRoGQWRtaW5zGgcKA01T
      UBIAIg8KC0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMS
      ACoGQWRtaW5z

